
spring:
  application:
    name: API-GATEWAY-Prod


eureka:
    instance:
      prefer-ip-address: true
    client:

      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8012/eureka
